---
handler:
  path: '/home/lambda/lambda_handler.py'
  module_name: 'lambda_handler'
broker:
  servers:
    - 'nats://localhost:4222'
request_subject: 'request.*'
response_subject_prefix: 'response'
tasks_termination_timeout: 0.2
log_level: DEBUG
